# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8,11,17]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Build with Maven
      run: mvn -B clean verify

    - name: Run integration tests - Manage Travels
      working-directory: ./app/travel_processor
      run: |
        npm ci
        npm run test:java -- --ci

  e2ekymatest:
    name: End to End Kyma Tests
    # if: ${{ github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'deploy-kyma') }}  # run only if label is set
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setting up environment
        run: |
          npm i -g @sap/cds-dk
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli
          mkdir ${HOME}/kyma-binaries
          export PATH=${HOME}/kyma-binaries/:$PATH
          mkdir ${HOME}/.kube
          echo "${{secrets.KUBE_CONFIG}}" | base64 --decode > ${HOME}/.kube/config
          (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.23.0/pack-v0.23.0-linux.tgz" | tar -C ${HOME}/kyma-binaries/ --no-same-owner -xzv pack)
          wget "https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz"
          tar -xvzf helm-v3.8.0-linux-amd64.tar.gz
          mv linux-amd64/helm ${HOME}/kyma-binaries/helm
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          mv ./kubectl ${HOME}/kyma-binaries/kubectl

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.IMAGEREGISTRY}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: End to End testing
        run: |
          releaseName=sflightjava
          deploymentName=srv
          releaseNamespace=e2e-kyma-test
          appPrefix=${releaseName}-${deploymentName}-${releaseNamespace}
          cds add helm --force
          cds add helm:hana_deployer
          cds add helm:xsuaa
          cds build --production
          hana_image=${{secrets.IMAGEREGISTRY}}/test/bookshop-hana-deployer
          srv_image=${{secrets.IMAGEREGISTRY}}/test/bookshop-srv
          pack build ${hana_image} --path db --buildpack gcr.io/paketo-buildpacks/nodejs --builder paketobuildpacks/builder:base
          mvn package
          pack build ${srv_image} --path srv/target/*-exec.jar --buildpack gcr.io/paketo-buildpacks/sap-machine --buildpack gcr.io/paketo-buildpacks/java --builder paketobuildpacks/builder:base --env SPRING_PROFILES_ACTIVE=cloud
          cp ./chart/xs-security.json xs-security.json.tmp && jq '. |= . + {"authority":"$XSAPPNAME.admin"}' xs-security.json.tmp >./chart/xs-security.json && rm xs-security.json.tmp
          docker push ${hana_image}
          docker push ${srv_image}
          helm install ${releaseName} ./chart --namespace ${releaseNamespace} --set global.imagePullSecret.name=${{secrets.IMAGEPULLSECRET}} --set global.domain=${{secrets.DOMAIN}}  --set srv.bindings.db.fromSecret=bookshop-db --set srv.image.repository=${srv_image} --set hana_deployer.image.repository=${hana_image} --set hana_deployer.bindings.hana.fromSecret=bookshop-db --set xsuaa.parameters.xsappname=bookshop-e2e-test --set srv.resources.limits.cpu=2000m --set srv.resources.limits.memory=2G --set srv.resources.requests.cpu=1000m --set srv.resources.requests.memory=2G
          kubectl rollout status deployment ${releaseName}-${deploymentName} --timeout=3m
          curl --max-time 10 --retry 5 --retry-delay 3 -f -LI -k https://${appPrefix}.${{secrets.DOMAIN}}
          xsuaaSecret=$(echo $(kubectl get secret ${releaseName}-${deploymentName}-${xsuaaKey} -o json))
          clientIDEncoded=$(jq '.data.clientid' <<< "$xsuaaSecret")
          clientSecretEncoded=$(jq '.data.clientsecret' <<< "$xsuaaSecret")
          clientID=`echo -n $clientIDEncoded | base64 --decode`
          clientSecret=`echo -n $clientSecretEncoded | base64 --decode`
          urlEncoded=$(jq '.data.url' <<< "$xsuaaSecret")
          url=`echo -n $urlEncoded | base64 --decode`
          appPrefix=${releaseName}-${deploymentName}-${releaseNamespace}
          appUrl=https://${appPrefix}.${{secrets.DOMAIN}}
          idPwdFormatted="$clientID:&clientSecret"
          idPwd=`echo -n $idPwdFormatted | base64`
          response=$(curl --location --request GET ${url}/oauth/token?grant_type=client_credentials&response_type=token --header 'Authorization: Basic ${idPwd}')
          accessToken=$(jq '.access_token' <<< "$response")
          status=$(curl -H "Content-Type: application/json" -H "Authorization: Bearer ${accessToken}" ${appUrl}/${endpoint})
          `if [ $status == 200 ]
          then
            exit 0
          else
            exit 1`

      - name: Helm Uninstall
        run: |
          helm uninstall sflight --namespace ${releaseNamespace}
          
          
